name: CI
on:
  - push
  - pull_request
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Zig
        run: |
          sudo apt install xz-utils
<<<<<<< HEAD
          sudo sh -c 'wget -c https://pkg.machengine.org/zig/zig-linux-x86_64-0.11.0-dev.3883+7166407d8.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
=======
          sudo sh -c 'wget -c https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.3947+89396ff02.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
>>>>>>> ab6a07601f85eb9d2fcfa74f6dc8716c05ee576a
      - name: build
        run: zig build
  x86_64-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Zig
        run: |
          $ProgressPreference = 'SilentlyContinue'
<<<<<<< HEAD
          Invoke-WebRequest -Uri "https://pkg.machengine.org/zig/zig-windows-x86_64-0.11.0-dev.3883+7166407d8.zip" -OutFile "C:\zig.zip"
=======
          Invoke-WebRequest -Uri "https://ziglang.org/builds/zig-windows-x86_64-0.11.0-dev.3947+89396ff02.zip" -OutFile "C:\zig.zip"
>>>>>>> ab6a07601f85eb9d2fcfa74f6dc8716c05ee576a
          cd C:\
          7z x zig.zip
          Add-Content $env:GITHUB_PATH "C:\zig-windows-x86_64-0.11.0-dev.3947+89396ff02\"
      - name: build
        run: zig build
  x86_64-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Zig
        run: |
          brew install xz
<<<<<<< HEAD
          sudo sh -c 'wget -c https://pkg.machengine.org/zig/zig-macos-x86_64-0.11.0-dev.3883+7166407d8.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
=======
          sudo sh -c 'wget -c https://ziglang.org/builds/zig-macos-x86_64-0.11.0-dev.3947+89396ff02.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
>>>>>>> ab6a07601f85eb9d2fcfa74f6dc8716c05ee576a
      - name: build
        run: zig build
        env:
          AGREE: true
